### ISSUE TITLE
Cross-Check 'Docker basics' - 'excluz1v'

### ISSUE THREAD

**Issue by excluz1v** [rolling-scopes-school/support#380]
1 Task https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/docker-basics.md
2 Repo  https://github.com/excluz1v/nodejs2021Q4-service   branch docker-basics
3 Form check  https://boring-ride-216864.netlify.app/
3 130/130
4 Самопроверка
Базовая реализация:
Наличие в Readme.md секции с инструкцией как запустить приложение +20 баллов
Используется user-defined bridge + 30 баллов
При возникновении ошибки контейнер должен перезапускается автоматически +30 баллов
Логи и файлы базы данных хранятся в volumes, а не в контейнере + 30 баллов
Продвинутая реализация
Итоговый docker-образ с приложением имеет размер меньше 300 мб +20 баллов

Штрафы: отсутствуют

Прошу проверить задание, т.к. в стране, где я проживаю (Казахстан) был ограничен интернет с 05.01.2022г. Многие сервисы, в том числе github, app.rs.school, дискорд  были не доступны.
Также об этом было объявлено в дискорде: https://discord.com/channels/755676888680366081/925789520107020388/929964219963703427

Спасибо за понимание.

**Comment by AlreadyBored** [comment]
Ваша оценка - 60 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) При возникновении ошибки контейнер перезапускается автоматически 
Отзыв: Application is broken because of completely invalid Dockerfile
2) Итоговый docker-образ с приложением имеет размер меньше 300 мб 
Отзыв: After uncommenting installation of dependencies application image size is 446 Mb. You shouldn't break application for achieving lesser size.
Выполненные пункты:
1) Наличие в Readme.md секции с инструкцией как запустить приложение 

2) Используется user-defined bridge 

3) Логи и файлы базы данных хранятся в volumes, а не в контейнере 

Штрафы:
1) При изменении файлов в папке src приложение не перезапускается 
Отзыв: Application is broken so it doesn't works
