### ISSUE TITLE
Cross-Check File Manager - alisabox

### ISSUE THREAD

**Issue by alisabox** [rolling-scopes-school/support#575]
- Репозиторий: https://github.com/alisabox/node-nodejs-basics (ветка task-2)
- Задание: https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md
- Форма для проверки: https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md
- Скриншот с оценками за cross-check:
  - Проверяющий №1 (претензий к оценке нет)
![image](https://user-images.githubusercontent.com/77010822/174487509-d8fdafd0-92b4-4b5e-b74f-650fe2f9ca3b.png)
  - Проверяющий №2 (оценка выглядит сильно заниженной)
![image](https://user-images.githubusercontent.com/77010822/174487589-3ccbf7d9-e1b7-4a4b-803b-a2a7c4dba7de.png)

- Своя оценка: 310 / 320
Есть небольшие баги, которые нашел первый проверяющий, но основные требования задания выполнены.

- Балл за cross-check из Score: 250/320

**Comment by ML6503** [comment]
Your evaluation - 219 points 
Assignment items feedback:
Not implemented / not credited points:
1) Read file and print it's content in console 
Feedback: command "cat test.txt"  replied with "Cannot read the file test.txt"
2) Rename file 
Feedback: command "rn test1.txt test2.txt" doesn't work
3) Copy file 
Feedback: Command 'p test1.txt [path_name]/test.txt' replies with annot copy file
4) Move file 
Feedback: Applicaiton replies with " errno: -4058, code: 'ENOENT'," to the command "mv test1.txt to [folder_path]"
5) Delete file 
Feedback: Application replies with "Cannot remove file" to command "rm test1.txt" 

6) Get CPU architecture for which Node.js binary has compiled 
Feedback: Command "hash path_to_file" replies with "Such file doesn't exist"
7) Calculate hash for file and print it into console 
Feedback: on hash command get reply "Such file doesn't exist"
Partially implemented points:
1) Go to dedicated folder from current directory 
Feedback: Command to go to other root leads to application folder. Command to go to folder with white space in naming leads to error No such directory
2) Compress file (using Brotli algorithm) 
Feedback: file compressed to task-2 folder instead of C:\Users\... folder and reply received cannot decompressed
3) Decompress file (using Brotli algorithm) 
Feedback: file decompressed to task-2 folder instead of C:\Users\... folder and reply received cannot decompressed
Fully implemented points:
1) Application accepts username and prints proper message 

2) Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed 

3) Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail 

4) Operation fail doesn't crash application 

5) Go upper from current directory 

6) List all files and folders in current directory 

7) Create empty file 

8) Get EOL (default system End-Of-Line) 

9) Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them) 

10) Get home directory 

11) Get current *system user name* (Do not confuse with the username that is set when the application starts) 

12) All files operations with reading/writing should be performed using Streams API 

13) Codebase is written in ESM modules instead of CommonJS 

14) Codebase is separated (at least 7 modules)
