### ISSUE TITLE
Cross-Check Plants #2 - olegthunder

### ISSUE THREAD

**Issue by olegthunder** [rolling-scopes-school/support#844]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/olegthunder-JSFEPRESCHOOL2022Q4/plants/) 
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/olegthunder-JSFEPRESCHOOL2022Q4.git)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/118740298/214991216-7233b43c-f395-4d1b-9587-3c771588afaf.png)
6. A final score after self-assessment, with comments
Проверяющий не поставил балл в поле для выставления баллов, хотя в отзыве оценил работу на максимум баллов - 75. Пытался связаться с ним в дискорде, в комментариях rsapp - безрезультатно. Т.к. проверяющих было только трое эти 0 баллов пошли в среднюю оценку. Оцениваю свою работу на 75 баллов.
7. A cross-check score of your Score 50 / 75

**Comment by lyutails** [comment]
hey there o/

1. 768 layout
- header +2
- welcome (max 3) +2
**text in button wraps**
![image](https://user-images.githubusercontent.com/101958335/218465163-b3ac55af-2c2a-47e1-a4fe-eb09c8302721.png)
![image](https://user-images.githubusercontent.com/101958335/218465221-629e93e6-0404-4530-9801-8322bf92c6d9.png)
- about +4
- service +4
- prices (max 4) +3
**more than 10px difference for the title in prices**
![image](https://user-images.githubusercontent.com/101958335/218465575-63dfc489-601f-4a08-9645-c6ceba7c6d57.png)
![image](https://user-images.githubusercontent.com/101958335/218465665-3fa4d5c9-d071-4d87-a796-9f777254693d.png)
- contacts (max 4) +3
**woman pic distortion in contacts more than 10px**
![image](https://user-images.githubusercontent.com/101958335/218465931-aa757ab1-bf4e-4f8e-84e7-951615fa2552.png)
![image](https://user-images.githubusercontent.com/101958335/218466052-c385400f-e979-4009-9d6f-b3dc80229997.png)
- footer +3
**by design in footer it's just "github" - "olegthunder" breaks whole line being in the center, maybe would be better to make it centered**
![image](https://user-images.githubusercontent.com/101958335/218466986-096880c9-0348-4955-b605-02a6ddd556b1.png)
2. 380 layout
- header +2
- welcome +3
- about +4
- service +4
- prices +4
- contacts +4
- footer +3
3. No scrolls
- from 1440px to 380px (max 7) +0
**scroll appears on width between 381 and 398**
![image](https://user-images.githubusercontent.com/101958335/218464842-a663f1cb-f77c-407a-b267-e0da1afe6ac1.png)
- from 380px to 320px (max 8) +0
**scroll appears on width between 341 and 345**
![image](https://user-images.githubusercontent.com/101958335/218463875-841f562c-07c0-41c4-985d-311b8449ba1d.png)
4. Burger
- when width is 380px nav menu disappears and burger icon appears +2
- menu slowly appears by click on burger +4
- burger menu follows design +4
- you can close menu by click on ❎ +4
- links in menu smoothly scrolls to sections +4
- by click on nav link in menu - menu smoothly disappears +4

to avoid misunderstandings - we subtract from 85 (max score is 75) and result is 85 - 18 = 67

**Final score: 67**

@helenakrasnova
take a look at please
@Luffi2539
take a look at please

**Comment by valerydluski** [comment]
score updated

**Comment by olegthunder** [comment]
Спасибо за проверку, но там нет скроллов.
*scroll appears on width between 341 and 345*
[image: image.png][image: image.png]
*scroll appears on width between 381 and 398 *
А здесь он есть с 381 до 388 только на десктопе, на мобилке его нет. Хотя
точно помню, что на момент проверки Plants 2 прокрутки не было и остальные
проверяющие не снизили за это балл. Может верстка слегка поехала уже на
Plants 3, когда кое-что дорабатывал


вт, 14 февр. 2023 г. в 00:20, Valery ***@***.***>:
