### ISSUE TITLE
Cross-Check 'Plants #2' Sam2508

### ISSUE THREAD

**Issue by Sam2508** [rolling-scopes-school/support#848]
1. https://rolling-scopes-school.github.io/sam2508-JSFEPRESCHOOL2022Q4/plants/
2. https://github.com/rolling-scopes-school/sam2508-JSFEPRESCHOOL2022Q4
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part2.md
4. https://rolling-scopes-school.github.io/checklist/
5. https://user-images.githubusercontent.com/119897472/215120895-767a9c3c-bce4-401d-b897-8c2e82560b81.png
6. Самопроверка- 75 баллов 
Все пункты выполнены ТЗ:
Выполненные пункты:1) Блок header; 2) Секция welcome; 3) Секция about; 4) Секция service; 5) Секция prices; 6) Секция contacts 7) Блок footer; 8) Блок header; 9) Секция welcome; 10) Секция about; 11) Секция service; 12) Секция prices 13) Секция contacts 14) Блок footer 15) нет полосы прокрутки при ширине страницы от 1440рх до 380px 16) нет полосы прокрутки при ширине страницы от 380px до 320рх 7) при ширине страницы 380рх панель навигации скрывается, появляется бургер-иконка 18) при нажатии на бургер-иконку плавно появляется адаптивное меню 19) адаптивное меню соответствует цветовой схеме макета 20) при нажатии на крестик адаптивное меню плавно скрывается уезжая за экран 21) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям (все, кроме Account, она пока просто закрывает меню) 22) при клике по ссылке в адаптивном меню адаптивное меню плавно скрывается, также скрытие меню происходит если сделать клик вне данного окна 
7. Cross-Check: 50 баллов
P.S. Из 4-х человек мою работу проверило 3 человека (2 человека выставило по 75 баллов, 1 человек - 0 баллов ссылаясь на не рабочие ссылки, хотя я предоставил ему и альтернативные ссылки, который были проверены!).

**Comment by lyutails** [comment]
hey there o/

1. 768 layout
- header +2
- welcome +3
- about +4
- service +4
- prices +4
- contacts (max 4) +2
**no woman pic in contacts section, that's why don't fit design and creates huge difference in px**
![image](https://user-images.githubusercontent.com/101958335/218461207-06ff65f7-6461-4fb8-9a31-f9cde7eb2916.png)
- footer +3
2. 380 layout
- header +2
- welcome +3
- about +4
- service +4
- prices +4
- contacts +4
- footer (max 3) +2
**social media icons a bit distorted**
![image](https://user-images.githubusercontent.com/101958335/218460210-c1cda23a-b884-4c72-8509-9e3a810fa1e1.png)
3. No scrolls
- from 1440px to 380px +7
- from 380px to 320px +8
4. Burger
- when width is 380px nav menu disappears and burger icon appears +2
- menu slowly appears by click on burger +4
- burger menu follows design +4
- you can close menu by click on ❎ +4
- links in menu smoothly scrolls to sections +4
- by click on nav link in menu - menu smoothly disappears +4

to avoid misunderstandings - we subtract from 85 and result is 85 - 3 = 82, though max score for this task is 75

**Final score 75**

@helenakrasnova
take a look at please
@Luffi2539
take a look at please

**Comment by valerydluski** [comment]
score updated
