### ISSUE TITLE
Cross-Check 'Task CSS Bayan' - SashaSNKy

### ISSUE THREAD

**Issue by SashaSNky** [rolling-scopes-school/support#862]
**Уважаемые RS АКТИВИСТЫ, так получилось что с 06.03.2023 по 13.03.2023г. находился в больнице (09.03.2023 проведена операция). По этой причине выполнить задание [Codejam#1 2023Q1](https://github.com/DrDiman/CSS-Bayan-task) не было возможности. Огромная просьба найти время и проверить задание, оценить и оставить свои замечания и предложения!!! 
(если необходимы подтверждающие документы - могу скинуть по вашему запросу. Пишите Discord: AlexSN (@SashaSNky), mail: sanek-avto@yandex.by. 
Заранее спасибо.  
Dear RS ACTIVISTS, it so happened that from 03/06/2023 to 03/13/2023 I was in the hospital (03/09/2023 surgery). For this reason, it wasn't possible to complete the [Codejam#1 2023Q1](https://github.com/DrDiman/CSS-Bayan-task) task. Please, find the time and check the task, evaluate and leave your comments and suggestions!!!
(if supporting documents are needed, I can send them at your request. Write to Discord: AlexSN (@SashaSNky), mail: sanek-avto@yandex.by.
Thank you!!!**

1.  - [A link to your deployed project](https://sashasnky.github.io/cssBayan/cssBayan/index.html)
2. - [A link to the project repository on Github](https://github.com/SashaSNky/cssBayan)
3. - [A link to the task](https://github.com/DrDiman/CSS-Bayan-task)
4. A Link to the checklist for evaluating the task (if it exists)
    - [A Link to the checklist for evaluating the task](https://rolling-scopes-school.github.io/checklist/)
5.  A final score after self-assessment, with comments
Ваша оценка - 139 баллов 
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) Pull Request from gh-pages branch to main branch is open. Pull Request name is equal to the task name. Description of the Pull Request was done accordingly to the guideline (https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr). The link to this Pull Request was submitted to the cross check form. This Pull Request was NOT merged 
Отзыв: Не возможно по техническим причинам добавит ссылку в cross check Form, т.к. прошли сроки сдачи 
Выполненные пункты:
1) Public repository with name "cssBayan" created 

2) Branch gh-pages created 

3) The "cssBayan" folder has been created in the gh-pages branch. Deploy is available via link, link example: https://${YOUR_GITHUB_NAME}.github.io/cssBayan/cssBayan/index.html 

4) There are at least 5 commits in the gh-pages branch with the history of the project development 

5) The commits are called accordingly to the guideline (https://docs.rs.school/#/git-convention), each commit contains a time-stamp. Time-stamp can be at any language. Accordingly to your time-stamp should be clear, when this commit was done: day of the week, month, day, year, time with seconds (the order can vary) e.g. Commit message example: feat: add basic page layout (Mon, Sep 13, 2021 10:25:24 PM) 

6) The accordion component is centered on the screen, with equal indents on the left and right 

7) Icons, meme texts and meme images are exist 

8) Placement of the meme, icons and meme text are the same as in provided example gif images 

9) Smooth change (transition) of the meme images and icons is done 

10) Responsive design with three breakpoints for mobile, tablet, and desktop exist. Accordion is displayed correctly at mobile 320x568, tablet 820x1180, desktop 1920x1080. (Note: breakpoints don't have to be 320x568, 820x1180, 1920x1080) 

11) All visual effects when the cursor is hovering over the memes, when the mouse is down on a meme, and when a meme is selected are implemented 

12) The entire row (text, icon, and meme image) clickable 

13) Cursor over the memes (hover) effect only exists for devices that can support hover. This means that the touch device (phone, tablet) doesn't have hover effects, and desktop does have hover effects 

14) The cursor when it is hovering over the rows of the accordion is changing 

15) Only flexible dimensions are used (rem, em, %, vh, vw, fr and etc.). The accordion is responsive 

16) All blocks/parts of the accordion are in base flow of the dom elements. All elements are not positioned with top, left, right, bottom. float is not used. The value of position is only static. Note: usage of display: none is ALLOWED 

17) Pseudo-elements are not used (note 1: pseudo-classes are ALLOWED; note 2: pseudo-elements ONLY from FontAwesome are allowed) 

18) Initially, the first meme should be expanded 

19) Font size is changed at each device (mobile, tablet, desktop)

**Comment by helenakrasnova** [comment]
1) поправьте ссылки в md
2) сделайте pull request в репозитории своего задания согласно требованиям

**Comment by SashaSNky** [comment]
Поправлены ссылки в md
pull request в репозитории своего задания сделан

**Comment by SashaSNky** [comment]
Спасибо. Все поправлено. 16.03.2023, 18:48, "helenakrasnova" ***@***.***>: поправьте ссылки в mdсделайте pull request в репозитории своего задания согласно требованиям—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by lyutails** [comment]
hey there o/
good job :)

1. Public repository with name "cssBayan" created +5
2. Branch gh-pages created +5
3. The "cssBayan" folder has been created in the gh-pages branch. Deploy is available via link, link example: https://${YOUR_GITHUB_NAME}.github.io/cssBayan/cssBayan/index.html +5
4. There are at least 5 commits in the gh-pages branch with the history of the project development +5
5. The commits are called accordingly to the guideline (https://docs.rs.school/#/git-convention), each commit contains a time-stamp. Time-stamp can be at any language. Accordingly to your time-stamp should be clear, when this commit was done: day of the week, month, day, year, time with seconds (the order can vary) e.g. Commit message example: feat: add basic page layout (Mon, Sep 13, 2021 10:25:24 PM) (max score +5) **Last commit's name doesn't follow guideline and doesn't contain time-stamp** **+4** 
![image](https://user-images.githubusercontent.com/101958335/226074839-a58e83eb-a380-4113-ac4a-2a51a54d2a8f.png)
6. Pull Request from gh-pages branch to main branch is open. Pull Request name is equal to the task name. Description of the Pull Request was done accordingly to the guideline (https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr). **The link to this Pull Request was not submitted to the cross check form as deadline was already over.** This Pull Request was NOT merged  (would be better to write pr title as CSS Bayan, but yours is like in schedule so that's not mistake) (max score +5) **+4**
7. The accordion component is centered on the screen, with equal indents on the left and right +10
8. Icons, meme texts and meme images are exist +5
9. Placement of the meme, icons and meme text are the same as in provided example gif images +5
10. Smooth change (transition) of the meme images and icons is done +20
11. Responsive design with three breakpoints for mobile, tablet, and desktop exist. Accordion is displayed correctly at mobile 320x568, tablet 820x1180, desktop 1920x1080. (Note: breakpoints don't have to be 320x568, 820x1180, 1920x1080) +10 
**NB:** atm on small desktop less than 1920 font-size stays the same big, though we don't check it, but maybe you'll play around with your hover: none media to heal that (try to put all hovers in any-hover: hover media) 
12. All visual effects when the cursor is hovering over the memes, when the mouse is down on a meme, and when a meme is selected are implemented +10
13. The entire row (text, icon, and meme image) clickable +5
14. Cursor over the memes (hover) effect only exists for devices that can support hover. This means that the touch device (phone, tablet) doesn't have hover effects, and desktop does have hover effects +10
15. The cursor when it is hovering over the rows of the accordion is changing +5
16. Only flexible dimensions are used (rem, em, %, vh, vw, fr and etc.). The accordion is responsive +10
17. All blocks/parts of the accordion are in base flow of the dom elements. All elements are not positioned with top, left, right, bottom. float is not used. The value of position is only static. Note: usage of display: none is ALLOWED +5
18. Pseudo-elements are not used (note 1: pseudo-classes are ALLOWED; note 2: pseudo-elements ONLY from FontAwesome are allowed) +5
19. Initially, the first meme should be expanded +5
20. Font size is changed at each device (mobile, tablet, desktop) +5

140-2=138

**Final score: 138**

@helenakrasnova take a look at please
@valerydluski take a look at please

**Comment by helenakrasnova** [comment]
оценка выставлена
