### ISSUE TITLE
Cross-Check coffee-house-week1 - etwa22

### ISSUE THREAD

**Issue by etwa22** [rolling-scopes-school/support#931]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/week1/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/etwa22-JSFE2023Q4/tree/coffee-house
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week1.md
4. A Link to the checklist for evaluating the task (if it exists)

5. A screenshot of cross-checking marks
<img width="960" alt="2023-12-01 (1)" src="https://github.com/rolling-scopes-school/support/assets/104200121/5205162b-f169-444e-958a-d54631b2c0de">
<img width="960" alt="2023-12-01 (2)" src="https://github.com/rolling-scopes-school/support/assets/104200121/fcfaa24c-73d2-4c72-ad4e-b0de7da2e620">
<img width="960" alt="2023-12-01" src="https://github.com/rolling-scopes-school/support/assets/104200121/1d9dee17-ba79-4ea9-9c8e-2daa4831fd64">
6. A final score after self-assessment, with comments
78 баллов из 100, потому что:
1) <b>Menu</b> block on <b>menu</b> page: +6
Блок меню состоит из 2 блоков - offer + grid, у меня сделан только 1 блок - offer, поэтому 3 балла из 6.
2)  For positioning images in <b>About</b> block on <b>home</b> page and products in <b>Menu</b> block on <b>menu</b> page used <b>Flexbox</b> or <b>Grid</b> Layout: +4
У меня не сделан блок grid на странице меню, поэтому 2 балла из 4.
3) Navigation elements (except <b>Contact us</b>) lead to corresponding blocks on home <b>page</b> (anchor links): +4
Не работают ссылки на странице Меню, поэтому 2 балла из 4.
4) <b>Contact us</b> in navigation panel links to the <b>footer</b> block on its own page (anchor link): +2
1 балл из 2, потому что реализовано только для страницы Home
5) When clicking on the <b>Menu</b> buttons in <b>header</b> and <b>Enjoy</b> block on <b>home</b> page, it navigates to the menu page: +2
1 из 2 баллов, тк не работает кнопка в секции Enjoy
6) When clicking on the <b>Logo</b> in <b>header</b>, it navigates to the <b>home</b> page: +2
0 баллов - не реализовано
7) Each Coffee-card in the <b>Menu</b> section of the <b>Menu</b> page is interactive when hovering over any area of the card: +4
0 баллов - не реализовано
8) In the <b>footer</b> block, clicking on the link with phone number (all area including icon) should initiate a phone call: +2
0 баллов - не реализовано
9) In the <b>footer</b> block, clicking on the link with the address (all area including icon) should open a new browser tab with Google Maps displaying any location of your choice: +2
0 баллов - не реализовано
10) Interactivity of links and buttons is implemented according to Figma layout. Interactivity includes not only changing cursor's appearance, for example, using the <b>cursor: pointer</b> property, but also the use of other visual effects, such as changing the background color or font color, following the <b>Styleguide</b> in Figma layout: +4
1 балл из 4, так как интерактивность реализована только для навигации в хедере на странице Home + курсор поинтер на некоторых элементах
7. A cross-check score of your Score 
27

Еще считаю нужным дать пояснение по поводу ссылки на мою работу.  У меня моя работа открывается по ссылке https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/coffee-house/, доказательство - скриншот 
<img width="960" alt="2023-12-01 (3)" src="https://github.com/rolling-scopes-school/support/assets/104200121/20addcad-d74d-4818-b5d8-0abcae957ed5">.
Эту ссылку я засабмитила.
Когда я копировала эту ссылку для того, чтобы вставить в описание пулреквеста, она отобразилась вот так: https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/%D1%81offee-house/. Не понимаю, почему.
Трое проверяющих мне написали, что засабмиченная ссылка не открывается, я отправила им ссылку из описания пулреквеста. После этого двое проверяющих мою работу проверили, а третий проверяющий прочитал сообщение с новой ссылкой, но  проверять работу не стал, поставил 0 баллов, хотя до дедлайна оставалось еще 11 часов.

**Comment by haslie22** [comment]
@etwa22 
I assume that the letter "с" in the word "coffee" in your link is encoded as `%D1%81` because you used the Cyrillic letter "с" instead of the Latin one. Specifically, it is encoded as `%D1%81` in UTF-8, and your deployment does not open using the link where the letter "c" is written in Latin. Compare: the 1st link will open correctly, and the 2nd one won't open:

https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/сoffee-house/
https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/coffee-house/

According to the school rules, the reviewer may recheck your work, but they are not obliged to do so. Submitting the link and checking its correctness is the responsibility of the student, and this case is not covered by the appeal process. 
In the future, I recommend checking the links for correctness before starting the cross-check and ensuring that Cyrillic characters are not used in the links.

P.S. FYI, as you're working in school **private** repository, your cross-checkers don't see your PR at all — it's visible only to the school admins. I recommend using [this](https://docs.rs.school/#/private-repository?id=%d0%94%d0%be%d0%b1%d0%b0%d0%b2%d0%bb%d0%b5%d0%bd%d0%b8%d0%b5-%d1%81%d0%bf%d0%b8%d1%81%d0%ba%d0%b0-%d0%b2%d1%8b%d0%bf%d0%be%d0%bb%d0%bd%d0%b5%d0%bd%d1%8b%d1%85-%d0%b7%d0%b0%d0%b4%d0%b0%d0%bd%d0%b8%d0%b9-%d0%b8-%d0%ba%d0%be%d0%bd%d1%82%d0%b0%d0%ba%d1%82%d0%be%d0%b2-%d0%b2-%d0%bf%d1%80%d0%b8%d0%b2%d0%b0%d1%82%d0%bd%d1%8b%d0%b9-%d1%80%d0%b5%d0%bf%d0%be%d0%b7%d0%b8%d1%82%d0%be%d1%80%d0%b8%d0%b9) trick to ensure cross-checkers have higher possibility to find your work in case you've submitted the wrong link.

**Comment by helenakrasnova** [comment]
- Please change name of appeal via pattern Cross-Check 'название таска' - 'Ваше имя на Github' and add week-1.
- Change link in paragraph 1 to correct one.
- Provide link to your pull request for week-1 part, because in PR you have changes for week-2 too

Contact me if you have any questions

**Comment by etwa22** [comment]
Good evening,

I changed the title of issue, corrected the link in paragraph 1 and here it is the link to my pull request for task coffee-house-week1 from coffee-house to gh-pages - https://github.com/rolling-scopes-school/etwa22-JSFE2023Q4/pull/1

**Comment by helenakrasnova** [comment]
Your deploy should not have any changes related to week-2 or week-3
Please make a separate deploy for https://github.com/rolling-scopes-school/etwa22-JSFE2023Q4/pull/1 pull request in order to checker could see only week-1 implementation

**Comment by etwa22** [comment]
This is the link to my deploy for coffee house week-1, it hasn't any changes related to week-2 or week-3
https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/%D1%81offee-house/

**Comment by helenakrasnova** [comment]
this link is broken
link https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/coffee-house/ defenetely **has changes** related to week-2

**Comment by etwa22** [comment]
After several attemts I finally could create a new pull request for coffee-house week 1 https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/week1/

**Comment by helenakrasnova** [comment]
Your work will be checked if you make separate **deploy** for week 1.

**Comment by etwa22** [comment]
This link is a separate deploy for week1 https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/week1/

**Comment by helenakrasnova** [comment]
@etwa22 I'll ask you replace this link with the main link in the 1st item of pull request description

> This link is a separate deploy for week1 https://rolling-scopes-school.github.io/etwa22-JSFE2023Q4/week1/

**Comment by etwa22** [comment]
Done

**Comment by KristiBo** [comment]
**1. Checking validation of pages: +18**
- [x] The layout for both pages is validated and error-free according to the W3C Validator (https://validator.w3.org/): +12 (6 points per page)
- [x] Favicon is added to each page: +2
- [x] Each page has only one h1 element: +2
- [x] The URL of the menu page differs from the URL of the home page (e.g. your-site.com for the home page and your-site.com/menu for the menu page): +2

**2. The layout matches the design: +32/40**
- [x] header block on each page: +4
Замечание, снятие балла за которое посчитала избыточным - несоответствие макету кнопки меню на странице меню (она должна быть в активном состоянии, т.е. подчеркнута).
- [ ] Enjoy block on home page: +3/6
Пункт засчитан частично. Высота блока не соответствует макету: должна быть 644px, а у тебя 782px, из-за чего расположение текста и кнопки тоже не совпадает с макетом. Отклонение больше 10px.
- [x] Favourites Coffee block on home page: +6
- [x] About block on home page: +6
- [x] Mobile App block on home page: +6
- [ ] Menu block on menu page: +1/6
Пункт засчитан частично. В блоке присутствуют только кнопки переключения меню, карточек с кофе нет. Кнопок всего лишь 3 шт, а карточек должно быть 8 шт и они гораздо объемнее кнопок, поэтому самооценка в половину баллов за данный пункт необъективна. Кроме того, блок по высоте примерно на 40px больше, чем в макете, из-за чего для проверки футера на соответствие PerfectPixel пришлось сдвигать макет по вертикали.
- [x] footer block on each page: +6

**3. CSS Requirements: +8/10**
- [ ] For positioning images in About block on home page and products in Menu block on menu page used Flexbox or Grid Layout: +2/4
Пункт засчитан частично, т.к. на странице меню отсутствует блок с меню.
- [x] When scaling the browser page (<100%) or increasing the page width (>1440px), the layout of both pages is centered rather than shifted to the side and not stretched across the entire width: +4
- [x] The background color Body stretches across the entire width of the page: +2

**4. Interactivity: +11/32**
- [ ] Navigation elements (except Contact us) lead to corresponding blocks on home page (anchor links): +2/4
Пункт засчитан частично, т.к. навигация работает только на главной странице.
- [ ] Contact us in navigation panel links to the <footer> block on its own page (anchor link): +1/2
Пункт засчитан частично, т.к. навигация работает только на главной странице.
- [x] Smooth scrolling with anchor links: +2
Плавная прокрутка по якорям есть, хоть и на одной странице. Баллы не вычитала, т.к. выше уже был вычет за неработающие якоря на странице меню.
- [ ] When clicking on the Menu buttons in header and Enjoy block on home page, it navigates to the menu page: +1/2
Пункт засчитан частично, т.к. кнопка в блоке Enjoy не работает.
- [x] The Menu button in header on menu page is non-interactive: +2
- [ ] When clicking on the Logo in header, it navigates to the home page: 0/2
- [x] The active Coffee button in Menu block of Menu page is non-interactive: +2
- [ ] Each Coffee-card in the Menu section of the Menu page is interactive when hovering over any area of the card: 0/4
- [ ] In the <footer> block, clicking on the link with phone number (all area including icon) should initiate a phone call: 0/2
- [ ] In the <footer> block, clicking on the link with the address (all area including icon) should open a new browser tab with Google Maps displaying any location of your choice: 0/2
- [ ] Interactivity of links and buttons is implemented according to Figma layout. Interactivity includes not only changing cursor's appearance, for example, using the cursor: pointer property, but also the use of other visual effects, such as changing the background color or font color, following the Styleguide in Figma layout: 0/4
Пункт не засчитан, т.к. нет соответствия макету даже на тех элементах, где присутствует интерактивность. Если говорить о подчеркивании ссылок в header, то линия подчеркивания должна быть расположена на большем расстоянии и иметь большую высоту.
- [ ] Mandatory requirement for interactivity: smooth change in the appearance of an element on hover, without affecting adjacent elements: 1/4
Плавности нет даже на тех элементах, на которых есть hover. В css-свойствах на ссылки в header прописано transition: 0s. При наведении на ссылки соседние элементы не затрагиваются, но внешний вид меняется только у ссылок в header на главной странице. Засчитываю балл.

_**Итоговая оценка: 69 баллов.**_

Успехов в дальнейшем обучении! Ты молодец, хоть и не все пункты получилось выполнить.

**Comment by etwa22** [comment]
Огромное спасибо за проверку!

**Comment by etwa22** [comment]
Подскажите, пожалуйста, а будет ли исправлена оценка за задание по итогам рассмотрения issue? И нужны ли еще какие-то мои действия, например, закрыть issue?

**Comment by helenakrasnova** [comment]
будет исправлена, не нужно закрывать ишью


Я также заметила что финальная оценка по результатам кросс-чека у вас не 27 как описано а 54

**Comment by etwa22** [comment]
Я указала, что финальная оценка 27, потому что полученные по итогам проверки баллы делятся на 2, такой вес у таска. То есть 54/2=27. Если нужно указать 54, напишите, я исправлю

**Comment by helenakrasnova** [comment]
в ишью указывается оценка без учёта коэффициентов, можно не исправлять, это на будущее
