### ISSUE TITLE
Cross-Check 'File Manager' - 'Pavel151194'

### ISSUE THREAD

**Issue by Pavel151194** [rolling-scopes-school/support#947]
1. A link to your deployed project
    - Task doesn't require any deployment
2. A link to the project repository on Github.
    - [node-nodejs-file-manager](https://github.com/Pavel151194/node-nodejs-file-manager/tree/dev)
3. A link to the task
    - [Assignment: File Manager](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [Scoring: File Manager](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. Screenshots of cross-checking marks
![Screenshot_1](https://github.com/rolling-scopes-school/support/assets/83722045/9d8b1d58-7de9-4f86-a68a-a1b9800a4050)
![Screenshot_1](https://github.com/rolling-scopes-school/support/assets/83722045/14bb7616-225d-4c62-8288-568399ee12e3)

6. A final score after self-assessment, with comments
    - [Self-assessment is described in the according pull request](https://github.com/Pavel151194/node-nodejs-file-manager/pull/1)
7. A cross-check score of your Score
     - 279/330

**Comment by helenakrasnova** [comment]
Issue naming should be via rules: Cross-check 'name of task' - 'github'
and
A screenshot(s) has to be with **all** cross-checking marks

**Comment by Pavel151194** [comment]
> Issue naming should be via rules: Cross-check 'name of task' - 'github' and A screenshot(s) has to be with **all** cross-checking marks

@helenakrasnova naming was updated, screenshots of all marks was added

**Comment by haslie22** [comment]
### Basic Scope `240/240`

#### General `16/16`

- [x] Application accepts username and prints proper message: `6/6`
- [x] Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed: `10/10`

#### Operations fail `30/30`

- [x] Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail: `20/20`
- [x] Operation fail doesn't crash application: `10/10`

#### Navigation & working directory operations `40/40`

- [x] Go upper from current directory: `10/10`
- [x] Go to dedicated folder from current directory: `10/10`
- [x] List all files and folders in current directory: `20/20`

#### Basic operations with files `60/60`

- [x] Read file and print its content in console: `10/10`
- [x] Create empty file: `10/10`
- [x] Rename file: `10/10`
- [x] Copy file: `10/10`
- [x] Move file: `10/10`
- [x] Delete file: `10/10`

#### Operating system info `34/34`

- [x] Get EOL (default system End-Of-Line): `6/6`
- [x] Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them): `10/10`
- [x] Get home directory: `6/6`
- [x] Get current system user name: `6/6`
- [x] Get CPU architecture for which Node.js binary has compiled: `6/6`

#### Hash calculation `20/20`

- [x] Calculate hash for file: `20/20`

#### Compress and decompress operations `40/40`

- [x] Compress file (using Brotli algorithm): `20/20`
- [x] Decompress file (using Brotli algorithm): `20/20`

### Advanced Scope `90/90`

- [x] All operations marked as to be implemented using certain streams should be performed using Streams API: `30/30`
- [x] No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`): `20/20`
- [x] Codebase is written in ESM modules instead of CommonJS: `20/20`
- [x] Codebase is separated (at least 7 modules): `20/20`

### Penalties `0/-413`

- [ ] Any external tools/libraries are used: `-314`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-99`

There are some issues I've encountered while checking the app:

1. If I want to interact with files/folders whose names have whitespaces (like `test folder` or `test file.txt`), I need to wrap my path in quotes. So potentially, I should be able to do like this:
   `cd './Desktop/test folder'`
   Your app doesn't handle cases when paths are wrapped in quotes.
2. You can have several types of instances besides files or folders, like symbolic links or sockets. You could check for those when executing `ls` command.
3. It would be great if your app could handle cases where the user tries to decompress a compressed file into the folder where the original file is stored. You could implement the same logic for name changing that you used in the `cp` command in case if the destination path is the same.

Actually, as these cases aren't explicitly indicated in the task requirements, I see no reason to deduct points for that. Just keep it in mind for the future tasks 😉


### Total: `330/330 points`

**Comment by haslie22** [comment]
@helenakrasnova check please

**Comment by helenakrasnova** [comment]
@haslie22 thank you for review!

**Comment by ThorsAngerVaNeT** [comment]
Score was updated
