### ISSUE TITLE
Cross-Check 'File Manager' - 'pavalescoba'.

### ISSUE THREAD

**Issue by PavalEscoba** [rolling-scopes-school/support#948]
1. A link to your deployed project
    - there's no need to deploy smth;
2. A link to the project repository on Github.
    - [File Manager](https://github.com/PavalEscoba/file-manager-node)
3. A link to the task
    - [link to task](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link to checklist](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/14364049/aeaa62da-6e59-46ad-9032-99639eaefe94)

6. A final score after self-assessment, with comments
260/330
I didn't implement 6 tasks, but I had only ONE reviewer and he didn't count 5 more AT ALL. 
[Link to PR with self-assessment and comments](https://github.com/PavalEscoba/file-manager-node/pull/1)

7. A cross-check score of your Score 
150

You can also reach me out here https://t.me/miatla

**Comment by helenakrasnova** [comment]
A screenshot(s) has to be with **all** cross-checking marks
and
contacts of checkers should be hidden

**Comment by PavalEscoba** [comment]
> A screenshot(s) has to be with **all** cross-checking marks and contacts of checkers should be hidden

@helenakrasnova hello. i believe you mean **all** cross-checking marks for this particular task? 
If so this is the only mark I have, because I have only one reviewer.
Screenshot is updated.

**Comment by PavalEscoba** [comment]
@helenakrasnova having the following problem:
Reviewer didn't count these tasks:  

- Compress file (using Brotli algorithm),
- Decompress file (using Brotli algorithm)  

But here is the implementation. Recorded a gif: https://ibb.co/0K2Byr0  

Also reviewer set as undone following tasks:

- Streams API
- Codebase is separated (at least 7 modules)
- No synchronous Node.js API with asynchronous analogues is used  

But all of these tasks are implemented.
I understand that they are implemented not in an ideal way, and you can decrease a mark, but it's not 0.

**Comment by helenakrasnova** [comment]
Np, I see what have happened, for now you fixed issue according to rules, so status is help wanted

**Comment by PavalEscoba** [comment]
@helenakrasnova thank you very much, Helena ))

**Comment by haslie22** [comment]
### Basic Scope `170/240`

#### General `16/16`

- [x] Application accepts username and prints proper message: `6/6`
- [x] Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed: `10/10`

#### Operations fail `30/30`

- [x] Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail: `20/20`
- [x] Operation fail doesn't crash application: `10/10`

#### Navigation & working directory operations `0/40`

- [ ] Go upper from current directory: `10/10`
- [ ] Go to dedicated folder from current directory: `10/10`
- [ ] List all files and folders in current directory: `20/20`

#### Basic operations with files `30/60`

- [x] Read file and print its content in console: `10/10`
- [x] Create empty file: `10/10`
- [ ] Rename file: `10/10`
- [ ] Copy file: `10/10`
- [ ] Move file: `10/10`
- [x] Delete file: `10/10`

#### Operating system info `34/34`

- [x] Get EOL (default system End-Of-Line): `6/6`
- [x] Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them): `10/10`
- [x] Get home directory: `6/6`
- [x] Get current system user name: `6/6`
- [x] Get CPU architecture for which Node.js binary has compiled: `6/6`

#### Hash calculation `20/20`

- [x] Calculate hash for file: `20/20`

#### Compress and decompress operations `40/40`

- [x] Compress file (using Brotli algorithm): `20/20`
- [x] Decompress file (using Brotli algorithm): `20/20`

### Advanced Scope `78/90`

- [ ] All operations marked as to be implemented using certain streams should be performed using Streams API: `18/30`
- [x] No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`): `20/20`
- [x] Codebase is written in ESM modules instead of CommonJS: `20/20`
- [x] Codebase is separated (at least 7 modules): `20/20`

### Penalties `0/-413`

- [ ] Any external tools/libraries are used: `-314`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-99`

There are some issues I've encountered while checking the app:
1. I guess you were supposed to output only the folder name, not the whole path, when using `os --homedir`
2. It would be nice if you implemented the option to compress or decompress files without specifying the output file name, such as `compress ./test.txt my-folder`, or if specifying an extension did not result in operation failure, for instance, `compress ./test.txt my-folder/test.txt`. Your current implementation appears too restrictive.

But I don't see any reason to deduct points for these requirements, because all doubts are resolved in favor of the student.

3. This task had 5 requirements, which should have been implemented using the Streams API. However, only 3 of them (`cat`, `compress`, `decompress`) were implemented.  
Therefore, I deducted 12 points (2/5 of the overall task score for the requirement _"All operations marked as to be implemented using certain streams should be performed using Streams API"_) for the tasks that haven't been implemented (`cp`, `mv`).

### Total: `248/330 points`

**Comment by haslie22** [comment]
@helenakrasnova take a look please 👀

**Comment by ThorsAngerVaNeT** [comment]
Score was updated
