### ISSUE TITLE
Cross-Check 'File Manager' - 'NazarankaYuliya'

### ISSUE THREAD

**Issue by NazarankaYuliya** [rolling-scopes-school/support#949]
1. A link to your deployed project
    - no
2. A link to the project repository on Github.
    - [link](https://github.com/NazarankaYuliya/node-file-manager)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
![2024-02-12 12 06 01](https://github.com/rolling-scopes-school/support/assets/97028438/e8dd2bd0-1d21-4c9d-922e-cbdab98e05e6)

6. A final score after self-assessment, with comments: ***330 - all tasks are implemented and work correctly***.

7. A cross-check score of your Score  : ***255***

**Comment by haslie22** [comment]
### Basic Scope `240/240`

#### General `16/16`

- [x] Application accepts username and prints proper message: `6/6`
- [x] Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed: `10/10`

#### Operations fail `30/30`

- [x] Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail: `20/20`
- [x] Operation fail doesn't crash application: `10/10`

#### Navigation & working directory operations `40/40`

- [x] Go upper from current directory: `10/10`
- [x] Go to dedicated folder from current directory: `10/10`
- [x] List all files and folders in current directory: `20/20`

#### Basic operations with files `60/60`

- [x] Read file and print its content in console: `10/10`
- [x] Create empty file: `10/10`
- [x] Rename file: `10/10`
- [x] Copy file: `10/10`
- [x] Move file: `10/10`
- [x] Delete file: `10/10`

#### Operating system info `34/34`

- [x] Get EOL (default system End-Of-Line): `6/6`
- [x] Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them): `10/10`
- [x] Get home directory: `6/6`
- [x] Get current system user name: `6/6`
- [x] Get CPU architecture for which Node.js binary has compiled: `6/6`

#### Hash calculation `20/20`

- [x] Calculate hash for file: `20/20`

#### Compress and decompress operations `40/40`

- [x] Compress file (using Brotli algorithm): `20/20`
- [x] Decompress file (using Brotli algorithm): `20/20`

### Advanced Scope `90/90`

- [x] All operations marked as to be implemented using certain streams should be performed using Streams API: `30/30`
- [x] No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`): `20/20`
- [x] Codebase is written in ESM modules instead of CommonJS: `20/20`
- [x] Codebase is separated (at least 7 modules): `20/20`

### Penalties `0/-413`

- [ ] Any external tools/libraries are used: `-314`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-99`

There are some issues I've encountered while checking the app:

1. In requirements it is said: _"Starting working directory is current user's home directory"_. In your implementation starting directory is `node-file-manager`.
2. If I want to interact with files/folders whose names have whitespaces (like `test folder` or `test file.txt`), I need to wrap my path in quotes. So potentially, I should be able to do like this:
`cd 'Desktop/test folder/'`.
Your app doesn't handle cases when paths are wrapped in quotes.
3. You can have several types of instances besides files or folders, like symbolic links or sockets. You could check for those when executing `ls` command.
4. Would be great if the user could copy file to the same directory it's located. The name of the file could be changed somehow, e.g. `test.txt -> test_copy.txt`.
5. Use `.toString()` to display end-of-line in `os --EOL`, because in your current implementation the user can see only a blank line instead of `\n` or `\r\n`.
6. I guess you were supposed to output only the folder name, not the whole path, when running `os --homedir`.
7. It would be nice if you implemented the option to compress or decompress files without specifying the output file name, such as `compress ./test.txt my-folder`. Your current implementation appears too restrictive.

Actually, as these cases aren't explicitly indicated in the task requirements, I see no reason to deduct points for that. Just keep it in mind for the future tasks 😉

### Total: `330/330 points`

**Comment by haslie22** [comment]
@helenakrasnova take a look please 👀

**Comment by ThorsAngerVaNeT** [comment]
Score was updated
