### ISSUE TITLE
Cross-Check 'File Manager' - 'opty1712'.

### ISSUE THREAD

**Issue by Opty1712** [rolling-scopes-school/support#950]
1. A link to your deployed project
    - no
2. A link to the project repository on Github.
    - [link](https://github.com/Opty1712/node-nodejs-basics/pull/2/files )
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
<img width="1090" alt="image" src="https://github.com/rolling-scopes-school/support/assets/14236476/1d40f3ab-1bf3-4b1c-8e7b-0a35041c27cd">

6. A final score after self-assessment, with comments
330

7. A cross-check score of your Score 
0

No one made review of my task, I made three :(

**Comment by haslie22** [comment]
### Basic Scope `234/240`

#### General `16/16`

- [x] Application accepts username and prints proper message: `6/6`
- [x] Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed: `10/10`

#### Operations fail `30/30`

- [x] Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail: `20/20`
- [x] Operation fail doesn't crash application: `10/10`

#### Navigation & working directory operations `40/40`

- [x] Go upper from current directory: `10/10`
- [x] Go to dedicated folder from current directory: `10/10`
- [x] List all files and folders in current directory: `20/20`

#### Basic operations with files `54/60`

- [x] Read file and print its content in console: `10/10`
- [x] Create empty file: `10/10`
- [x] Rename file: `10/10`
- [ ] Copy file: `7/10`
- [ ] Move file: `7/10`
- [x] Delete file: `10/10`

#### Operating system info `34/34`

- [x] Get EOL (default system End-Of-Line): `6/6`
- [x] Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them): `10/10`
- [x] Get home directory: `6/6`
- [x] Get current system user name: `6/6`
- [x] Get CPU architecture for which Node.js binary has compiled: `6/6`

#### Hash calculation `20/20`

- [x] Calculate hash for file: `20/20`

#### Compress and decompress operations `40/40`

- [x] Compress file (using Brotli algorithm): `20/20`
- [x] Decompress file (using Brotli algorithm): `20/20`

### Advanced Scope `90/90`

- [x] All operations marked as to be implemented using certain streams should be performed using Streams API: `30/30`
- [x] No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`): `20/20`
- [x] Codebase is written in ESM modules instead of CommonJS: `20/20`
- [x] Codebase is separated (at least 7 modules): `20/20`

### Penalties `0/-413`

- [ ] Any external tools/libraries are used: `-314`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-99`

There are some issues I've encountered while checking the app:

1. You can have several types of instances besides files or folders, like symbolic links or sockets. You could check for those when executing `ls` command.
2. Use `.toString()` to display end-of-line in `os --EOL`, because in your current implementation the user can see only a blank line instead of `\n` or `\r\n`.
3. I guess you were supposed to output only the folder name, not the whole path, when running `os --homedir`.
4. It would be nice if you implemented the option to compress or decompress files without specifying the output file name, such as `compress ./test.txt my-folder`. Your current implementation appears too restrictive for the user.

But I don't see any reason to deduct points for these requirements, because all doubts are resolved in favor of the student.

5. I deducted 6 points for the implementation of the commands `cp` and `mv` (3 points for each). The specification states that the usage of these commands should look like this:
`cp path_to_file path_to_new_directory`
`mv path_to_file path_to_new_directory`
However, in your implementation, the second argument requires not only the path to the directory but also the name of the new file, which does not fully comply with the specification.

### Total: `324/330 points`

**Comment by haslie22** [comment]
@helenakrasnova  take a look please 👀

**Comment by helenakrasnova** [comment]
@haslie22 you are unicorn of appeals :cherry_blossom:

**Comment by Opty1712** [comment]
@haslie22, thank you!

**Comment by ThorsAngerVaNeT** [comment]
Score was updated
