### ISSUE TITLE
Cross-Check 'File manager' - 'Mat-Kon'

### ISSUE THREAD

**Issue by Mat-Kon** [rolling-scopes-school/support#952]
1. A link to your deployed project
    - no deployed
2. A link to the project repository on Github.
    - [link](https://github.com/Mat-Kon/File_manager)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - I haven't seen the check list
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/117714151/98501d97-69b6-448e-92fa-d045d656f3ef)

6. A final score after self-assessment, with comments
- 330/330
I have completed all the points of the task
7. A cross-check score of your Score 
- 279
I have one examiner and I disagree with his assessment

**Comment by helenakrasnova** [comment]
Issue naming should be via rules: Cross-check 'name of task' - 'github'

**Comment by Mat-Kon** [comment]
I fix this

**Comment by haslie22** [comment]
### Basic Scope `217/240`

#### General `16/16`

- [x] Application accepts username and prints proper message: `6/6`
- [x] Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed: `10/10`

#### Operations fail `20/30`

- [x] Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail: `20/20`
- [ ] Operation fail doesn't crash application: `0/10`

#### Navigation & working directory operations `40/40`

- [x] Go upper from current directory: `10/10`
- [x] Go to dedicated folder from current directory: `10/10`
- [x] List all files and folders in current directory: `20/20`

#### Basic operations with files `60/60`

- [x] Read file and print its content in console: `10/10`
- [x] Create empty file: `10/10`
- [x] Rename file: `10/10`
- [x] Copy file: `10/10`
- [x] Move file: `10/10`
- [x] Delete file: `10/10`

#### Operating system info `31/34`

- [x] Get EOL (default system End-Of-Line): `6/6`
- [ ] Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them): `7/10`
- [x] Get home directory: `6/6`
- [x] Get current system user name: `6/6`
- [x] Get CPU architecture for which Node.js binary has compiled: `6/6`

#### Hash calculation `20/20`

- [x] Calculate hash for file: `20/20`

#### Compress and decompress operations `30/40`

- [x] Compress file (using Brotli algorithm): `20/20`
- [ ] Decompress file (using Brotli algorithm): `10/20`

### Advanced Scope `90/90`

- [x] All operations marked as to be implemented using certain streams should be performed using Streams API: `30/30`
- [x] No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`): `20/20`
- [x] Codebase is written in ESM modules instead of CommonJS: `20/20`
- [x] Codebase is separated (at least 7 modules): `20/20`

### Penalties `0/-413`

- [ ] Any external tools/libraries are used: `-314`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-99`

There are some issues I've encountered while checking the app:

1. You can have several types of instances besides files or folders, like symbolic links or sockets. You could check for those when executing `ls` command.
2. When using `up` command, the display of the current directory does not match the actual directory: the actual directory is one level higher than the one displayed, it becomes clear when you use `ls` command after each `up` command.
3. Use `.toString()` to display end-of-line in `os --EOL`, because in your current implementation the user can see only a blank line instead of `\n` or `\r\n`.
4. I guess you were supposed to output only the folder name, not the whole path, when running `os --homedir`.

But I don't see any reason to deduct points for these requirements, because all doubts are resolved in favor of the student.

1. I deducted 10 points for the requirement _"Operation fail doesn't crash application"_.  
   When I try to start the application with predefined script `npm run start` or when I don't indicate username (e.g. `npm run start -- --username=`), the application crashes with the error:

<img width="763" alt="Снимок экрана 2024-02-16 в 00 01 27" src="https://github.com/rolling-scopes-school/support/assets/79032502/ae03c020-e9bb-4518-a8a0-701a43fecc52">

2. I deducted 10 points for the requirement _"Decompress file (using Brotli algorithm)"_ because every attempt to decompress a file, whether successful or not, leads to an error. Here is an example of the error encountered after successful decompression:

<img width="669" alt="Снимок экрана 2024-02-16 в 00 45 12" src="https://github.com/rolling-scopes-school/support/assets/79032502/6462e9e1-2534-49e0-80ae-f4f5347cf18a">

3. I also deducted 3 points for the requirement _"Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them)"_ , because you don't convert clock rate to GHz, the value your app displays is actually in **MHz** (1 GHz = 10^3 MHz):

<img width="647" alt="Снимок экрана 2024-02-16 в 00 51 44" src="https://github.com/rolling-scopes-school/support/assets/79032502/2f179651-3f95-472e-8030-111cc9f2768e">

### Total: `307/330 points`

**Comment by haslie22** [comment]
@helenakrasnova take a look please 👀

**Comment by Mat-Kon** [comment]
Thanks, all ok )

**Comment by ThorsAngerVaNeT** [comment]
Score was updated
