### ISSUE TITLE
Cross-Check 'File Manager' - 'KalmykovaElena'

### ISSUE THREAD

**Issue by KalmykovaElena** [rolling-scopes-school/support#956]
1. A link to your deployed project
    - not required
2. A link to the project repository on Github.
    - [link](https://github.com/KalmykovaElena/file-manager/pull/1)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/95431691/dfb5cb35-d62c-4faf-aef1-b97b081026b3)

6. A final score after self-assessment, with comments
 330 - All requirements are met
7. A cross-check score of your Score - the work has not been checked

**Comment by helenakrasnova** [comment]
в названии ишью указываем гитхаб свой, не дискорд-линк  
не нужно каждый ра новое ишью создавать, можно редактировать текущее

**Comment by KalmykovaElena** [comment]
Исправила, спасибо

**Comment by haslie22** [comment]
### Basic Scope `237/240`

#### General `16/16`

- [x] Application accepts username and prints proper message: `6/6`
- [x] Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed: `10/10`

#### Operations fail `30/30`

- [x] Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail: `20/20`
- [x] Operation fail doesn't crash application: `10/10`

#### Navigation & working directory operations `40/40`

- [x] Go upper from current directory: `10/10`
- [x] Go to dedicated folder from current directory: `10/10`
- [x] List all files and folders in current directory: `20/20`

#### Basic operations with files `60/60`

- [x] Read file and print its content in console: `10/10`
- [x] Create empty file: `10/10`
- [x] Rename file: `10/10`
- [x] Copy file: `10/10`
- [x] Move file: `10/10`
- [x] Delete file: `10/10`

#### Operating system info `31/34`

- [x] Get EOL (default system End-Of-Line): `6/6`
- [ ] Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them): `7/10`
- [x] Get home directory: `6/6`
- [x] Get current system user name: `6/6`
- [x] Get CPU architecture for which Node.js binary has compiled: `6/6`

#### Hash calculation `20/20`

- [x] Calculate hash for file: `20/20`

#### Compress and decompress operations `40/40`

- [x] Compress file (using Brotli algorithm): `20/20`
- [x] Decompress file (using Brotli algorithm): `20/20`

### Advanced Scope `90/90`

- [x] All operations marked as to be implemented using certain streams should be performed using Streams API: `30/30`
- [x] No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`): `20/20`
- [x] Codebase is written in ESM modules instead of CommonJS: `20/20`
- [x] Codebase is separated (at least 7 modules): `20/20`

### Penalties `0/-413`

- [ ] Any external tools/libraries are used: `-314`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-99`

There are some issues I've encountered while checking the app:

1. If I want to interact with files/folders whose names have whitespaces (like `test folder` or `test file.txt`), I need to wrap my path in quotes. So potentially, I should be able to do like this:
`cd 'Desktop/test folder/'`.
Your app doesn't handle cases when paths are wrapped in quotes.
2. You can have several types of instances besides files or folders, like symbolic links or sockets. You could check for those when executing `ls` command.
3. Would be great if the user could copy file to the same directory it's located. The name of the file could be changed somehow, e.g. `test.txt -> test_copy.txt`.
4. It would be nice if you implemented the option to compress or decompress files without specifying the output file name, such as `compress ./test.txt my-folder`. Your current implementation appears too restrictive for the user.
5. I guess you were supposed to output only the folder name, not the whole path, when running `os --homedir`.

But I don't see any reason to deduct points for these requirements, because all doubts are resolved in favor of the student.

6. I deducted 3 points for the requirement _"Get host machine CPUs info (overall amount of CPUs plus model and clock rate (in GHz) for each of them)"_, because you don't convert clock rate to GHz, the value your app displays is actually in **MHz** (1 GHz = 10^3 MHz):

<img width="586" alt="Снимок экрана 2024-02-16 в 01 32 42" src="https://github.com/rolling-scopes-school/support/assets/79032502/e4014f6d-6979-4328-9c97-5dacb4b12bc6">

### Total: `327/330 points`

**Comment by haslie22** [comment]
@helenakrasnova take a look please 👀

**Comment by ThorsAngerVaNeT** [comment]
Score was updated
