### ISSUE TITLE
Cross-Check 'Simple CRUD AI' - 'garnich'.

### ISSUE THREAD

**Issue by garnich** [rolling-scopes-school/support#958]
1. A link to your deployed project
    - not reqired
2. A link to the project repository on Github.
    - [https://github.com/garnich/node-crud-api/tree/crud-api-task](https://github.com/garnich/node-crud-api/tree/crud-api-task)
3. A link to the task
    - [https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/assignment.md](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/score.md](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/33061150/ee17aede-6d92-4063-beee-cccfd4ef8907)

6. A final score after self-assessment, with comments
Self check: 222

After receiving a rating (0) from Reviewer 1, I carried out an additional check and, having found out the reason, deleted the yarn.lock file from the repository (see details in comment on screenshot of cross-checking marks), which made it possible to conduct a normal cross-check (confirmation is the review dated 02/18/2024). Reviewer 1 did not conduct further verification, although he did read the comment I left.

Based on the results of this cross-check, the score was unreasonably reduced by 50%.

7. A cross-check score of your Score 
![image](https://github.com/rolling-scopes-school/support/assets/33061150/11ea7de4-f711-433a-9348-409a45a58f9a)

**Comment by helenakrasnova** [comment]
reviewer's contacts should be hidden

**Comment by garnich** [comment]
@helenakrasnova 
Updated.
![image](https://github.com/rolling-scopes-school/support/assets/33061150/f555ff65-3cfd-45f0-a245-edd78b9319f0)

**Comment by haslie22** [comment]
### Basic Scope `69/72`

- [x] The repository with the application contains a `Readme.md` file containing detailed instructions for installing, running and using the application: `10/10`
- [x] GET `api/users` implemented properly: `10/10`
- [x] GET `api/users/{userId}` implemented properly: `10/10`
- [x] POST `api/users` implemented properly: `10/10`
- [x] PUT `api/users/{userId}` implemented properly: `10/10`
- [ ] DELETE `api/users/{userId}` implemented properly: `7/10`

When trying to delete user with valid `userId`, server returns 200 instead of 204.

- [x] Users are stored in the form described in the technical requirements: `6/6`
- [x] Value of port on which application is running is stored in `.env` file: `6/6`

Would be nice to add smth like `.env.example` file to the repo.

### Advanced Scope `70/70`

- [x] Task implemented on Typescript: `30/30`
- [x] Processing of requests to non-existing endpoints implemented properly: `10/10`
- [x] Errors on the server side that occur during the processing of a request should be handled and processed properly: `10/10`
- [x] Development mode: npm script `start:dev` implemented properly: `10/10`
- [x] Production mode: npm script `start:prod` implemented properly: `10/10`

### Hacker Scope `60/80`

- [x] There are tests for API (not less than 3 scenarios): `30/30`
- [ ] There is horizontal scaling for application with a load balancer: `30/50`

The load balancer isn't working properly. It fails when handling the `userId`.  
For instance, after adding a user, I can view the list of all users via `GET api/users`, but I'm unable to retrieve details about a specific user via `GET api/users/{userId}` or delete it using `DELETE api/users/{userId}`.
Furthermore, the state of the database isn't consistent across different workers; it's only preserved for one worker.

### Penalties

- [ ] Any external tools except `nodemon`, `dotenv`, `cross-env`, `typescript`, `ts-node`, `ts-node-dev`, `eslint` and its plugins, `webpack` and its plugins, `prettier` and its plugins, `uuid`, `@types/*` as well as libraries used for testing: `-211`
- [ ] Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.): `-67`
- [ ] Missing PR or its description is incorrect: `-20`
- [ ] No separate development branch: `-20`
- [ ] Less than 3 commits in the development branch, not including commits that make changes only to `Readme.md` or similar files (`tsconfig.json`, `.gitignore`, `.prettierrc.json`, etc.): `-20`

### Total: `199/222 points`

**Comment by haslie22** [comment]
@AlreadyBored @ThorsAngerVaNeT take a look please 👀

**Comment by ThorsAngerVaNeT** [comment]
> @AlreadyBored @ThorsAngerVaNeT take a look please 👀

Thank you, Liza. I will update student score

**Comment by ThorsAngerVaNeT** [comment]
Score is updated
