### ISSUE TITLE
Cross-Check 'File Manager' - 'demos-prog'

### ISSUE THREAD

**Issue by demos-prog** [rolling-scopes-school/support#980]
1. A link to your deployed project
    - [link](https://github.com/demos-prog/rs-nodejs-course/pull/3)
2. A link to the project repository on Github.
    - [link](https://github.com/demos-prog/rs-nodejs-course/tree/file-manager)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![cross-checking marks](https://github.com/user-attachments/assets/300ec4cd-019d-4cf4-9e78-4d4d15d90afe)

6. A final score after self-assessment, with comments
300 - 300 is self-evaluating, my code only works with absolute file paths, and the relative path requirement was only specified for the CD command
7. A cross-check score of your Score 
281

**Comment by solidados** [comment]
# Final score - **216** of **330**
## Отзыв по пунктам ТЗ:

### Не выполненные/не засчитанные пункты:
1) Application accepts username and prints proper message  
2) No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)  
3) Codebase is separated (at least 7 modules)  

### Частично выполненные пункты:
1) Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail  
**Отзыв:** Application does not notify (throw an Error or something) if operation of non-existent path fail. E.g.: `cd /non-existant-folder`  
2) Read file and print it's content in console  
**Отзыв:** Command `cat` accepts only an absolete path even if you are trying to read the file in a current folder  
3) Rename file  
**Отзыв:** Command `rn` accepts only an absolete path even if you are trying to perform operation inside current folder  
4) Copy file  
**Отзыв:** Command `cp` accepts only an absolete path even if you are trying to perform operation inside current folder  
5) Move file  
**Отзыв:** Command `mv` accepts only an absolete path even if you are trying to perform operation inside current folder  
6) Delete file  
**Отзыв:** Command `rm` accepts only an absolete path even if you are trying to perform operation inside current folder  
7) Get EOL (default system End-Of-Line)  
**Отзыв:** Should simply print the result of `os --EOL`, not the such explanations as: `LF (Line Feed)` or `CRLF (Carriage Return + Line Feed)`  
8) Calculate hash for file  
**Отзыв:** Command `hash` accepts only an absolete path even if you are trying to perform operation inside current folder  
9) Compress file (using Brotli algorithm)  
**Отзыв:** Command `compress` accepts only an absolete path even if you are trying to perform operation inside current folder  
10) Decompress file (using Brotli algorithm)  
**Отзыв:** Command `decompress` accepts only an absolete path even if you are trying to perform operation inside current folder  

### Выполненные пункты:  
1) Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed  
2) Operation fail doesn't crash application  
3) Go upper from current directory  
4) Go to dedicated folder from current directory  
5) List all files and folders in current directory  
6) Create empty file  
7) Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)  
8) Get home directory  
9) Get current system user name  
10) Get CPU architecture for which Node.js binary has compiled  
11) All operations marked as to be implemented using certain streams should be performed using Streams API  
12) Codebase is written in ESM modules instead of CommonJS
