### ISSUE TITLE
Cross-Check - File Manager - @sqwezzy33333

### ISSUE THREAD

**Issue by sqwezzy33333** [rolling-scopes-school/support#981]
1. A link to your deployed project
    - [link](https://github.com/sqwezzy33333/file_manager/pull/1)
2. A link to the project repository on Github.
    - [link](https://github.com/sqwezzy33333/file_manager)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/73c16657-6588-47fd-9bbf-d1918964bfaa)
![image](https://github.com/user-attachments/assets/2af973bb-8515-4b4d-be0d-deea59a3b456)
![image](https://github.com/user-attachments/assets/a2e862b4-01f0-4755-9842-038f6273a1d6)
![image](https://github.com/user-attachments/assets/236e4e7a-5886-4951-aa88-8a7fb6d69f97)
![image](https://github.com/user-attachments/assets/03895e90-b395-456e-a900-15a8d05a5b3f)
![image](https://github.com/user-attachments/assets/32ae184f-fb07-4659-a77a-25946a6ff652)

6. A final score after self-assessment, with comments
I rate my work at the maximum score (330). I had 2 reviewers, the first one checked the 'main' branch, although the pull request was from the 'develop' branch, gave me a low rating. I can't contact him, he's anonymous. The second examiner rated my work correctly by the maximum score
7. A cross-check score of your Score:
267

**Comment by solidados** [comment]
# Final score - **327** of **330**
## Отзыв по пунктам ТЗ:
### Частично выполненные пункты:
1) Application accepts username and prints proper message 
**Отзыв**:  
Application does accept `username`, but it prints into console the default `username` as per script in `package.json`

### Выполненные пункты:
2) Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed  
3) Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail  
4) Operation fail doesn't crash application  
5) Go upper from current directory  
6) Go to dedicated folder from current directory  
7) List all files and folders in current directory  
8) Read file and print it's content in console  
9) Create empty file  
10) Rename file  
11) Copy file  
12) Move file  
13) Delete file  
14) Get EOL (default system End-Of-Line)  
15) Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)  
16) Get home directory  
17) Get current system user name  
18) Get CPU architecture for which Node.js binary has compiled  
19) Calculate hash for file  
20) Compress file (using Brotli algorithm)  
21) Decompress file (using Brotli algorithm)  
22) All operations marked as to be implemented using certain streams should be performed using Streams API  
23) No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)  
24) Codebase is written in ESM modules instead of CommonJS  
25) Codebase is separated (at least 7 modules)
