### ISSUE TITLE
Cross-Check 'file-manager' - 'seenpie'

### ISSUE THREAD

**Issue by seenpie** [rolling-scopes-school/support#982]
1. A link to your deployed project
    - [link](https://github.com/seenpie/file-manager-nodejs/pull/1)
2. A link to the project repository on Github.
    - [link](https://github.com/seenpie/file-manager-nodejs/tree/develop)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
(there are only 2 reviews)
![image](https://github.com/user-attachments/assets/f0c2dc0e-1ec4-4223-a357-60ffa1c9bc09)
![image](https://github.com/user-attachments/assets/6705b04d-65fc-4365-b406-81b8220e4560)

6. A final score after self-assessment, with comments
score: 310/330
## Basic Scope
 * General
   * **+6** Application accepts username and prints proper message
   * **+10** Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed

 * Operations fail
   * **+20** Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail
   * **+10** Operation fail doesn't crash application

 * Navigation & working directory operations implemented properly
   * **+10** Go upper from current directory
   * **+10** Go to dedicated folder from current directory
   * **+20** List all files and folders in current directory

 * Basic operations with files implemented properly
   * **+10** Read file and print it's content in console
   * **+10** Create empty file
   * **+10** Rename file
   * **+10** Copy file
   * **+10** Move file
   * **+10** Delete file

 * Operating system info (prints following information in console) implemented properly
   * **+6** Get EOL (default system End-Of-Line)
   * **+10** Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)
   * **+6** Get home directory
   * **+6** Get current _system user name_ (Do not confuse with the username that is set when the application starts)
   * **+6** Get CPU architecture for which Node.js binary has compiled

 * Hash calculation implemented properly  
   * **+20** Calculate hash for file

 * Compress and decompress operations
   * **+20** Compress file (using Brotli algorithm)
   * **+20** Decompress file (using Brotli algorithm)

 ## Advanced Scope
 * **+30** All operations marked as to be implemented using certain streams should be performed using Streams API
 * **+20** No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)
 * **+20** Codebase is written in ESM modules instead of CommonJS
 * **?20** Codebase is separated (at least 7 modules)

7. A cross-check score of your Score 
370

**Comment by solidados** [comment]
# Final score - **330** of **330**
## Отзыв по пунктам ТЗ:
All tasks and requirements are properly performed and fulfilled.  
I’d recommend to add some colors and more notifications, yet – it is performed satisfactory.

### Выполненные пункты:
1) Application accepts username and prints proper message  
2) Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed  
3) Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail  
4) Operation fail doesn't crash application  
5) Go upper from current directory  
6) Go to dedicated folder from current directory  
7) List all files and folders in current directory  
8) Read file and print it's content in console  
9) Create empty file  
10) Rename file  
11) Copy file  
12) Move file  
13) Delete file  
14) Get EOL (default system End-Of-Line)  
15) Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)  
16) Get home directory  
17) Get current system user name  
18) Get CPU architecture for which Node.js binary has compiled  
19) Calculate hash for file  
20) Compress file (using Brotli algorithm)  
21) Decompress file (using Brotli algorithm)  
22) All operations marked as to be implemented using certain streams should be performed using Streams API  
23) No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)  
24) Codebase is written in ESM modules instead of CommonJS  
25) Codebase is separated (at least 7 modules)
